packages:cyberflake:
  - '### Which (application|package|application or package) is this (bug
    report|feature request) for\?\n\nCyberflake\n'

packages:eslint-config:
  - '### Which (application|package|application or package) is this (bug
    report|feature request) for\?\n\nESLint config\n'

packages:import-sort:
  - '### Which (application|package|application or package) is this (bug
    report|feature request) for\?\n\nImport sort\n'

packages:prettier-config:
  - '### Which (application|package|application or package) is this (bug
    report|feature request) for\?\n\nPrettier config\n'

packages:stylelint-config:
  - '### Which (application|package|application or package) is this (bug
    report|feature request) for\?\n\nStylelint config\n'

packages:tsconfig:
  - '### Which (application|package|application or package) is this (bug
    report|feature request) for\?\n\nTSConfig\n'
