packages:api:
  - changed-files:
      - any-glob-to-any-file:
          - packages/api/*
          - packages/api/**/*

packages:cyberflake:
  - changed-files:
      - any-glob-to-any-file:
          - packages/cyberflake/*
          - packages/cyberflake/**/*
