packages:cyberflake:
  - changed-files:
      - any-glob-to-any-file:
          - packages/cyberflake/*
          - packages/cyberflake/**/*

packages:shared:
  - changed-files:
      - any-glob-to-any-file:
          - packages/shared/**/*

packages:eslint-config:
  - changed-files:
      - any-glob-to-any-file:
          - packages/shared/eslint-config/*
          - packages/shared/eslint-config/**/*

packages:import-sort:
  - changed-files:
      - any-glob-to-any-file:
          - packages/shared/import-sort/*
          - packages/shared/import-sort/**/*

packages:prettier-config:
  - changed-files:
      - any-glob-to-any-file:
          - packages/shared/prettier-config/*
          - packages/shared/prettier-config/**/*

packages:stylelint-config:
  - changed-files:
      - any-glob-to-any-file:
          - packages/shared/stylelint-config/*
          - packages/shared/stylelint-config/**/*

packages:tsconfig:
  - changed-files:
      - any-glob-to-any-file:
          - packages/shared/tsconfig/*
          - packages/shared/tsconfig/**/*

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - docs/**/*
