/**
 * Core rules applied identically to JavaScript and TypeScript sources.
 *
 * Covers three concerns:
 * - correctness hardening beyond `eslint:recommended`,
 * - complexity and size limits,
 * - restrictions and consistent style.
 *
 * Rules that have a `@typescript-eslint` twin do NOT belong here — they live
 * in `./typescript.ts` as off/on pairs so the two versions can never fire
 * together.
 * @packageDocumentation
 */

import type { Linter } from 'eslint';

/**
 * Environment-agnostic core rule set shared by every preset.
 */
export const SHARED_RULES: Linter.RulesRecord = {
  /* ── Possible errors not in recommended ─────────────────────────────── */
  'no-await-in-loop': 'error',
  'no-promise-executor-return': 'error',
  'no-template-curly-in-string': 'error',
  'no-unmodified-loop-condition': 'error',
  'no-unreachable-loop': 'error',
  'require-atomic-updates': 'error',

  /* ── Complexity & size limits ────────────────────────────────────────── */
  complexity: 'error',
  'max-classes-per-file': 'error',
  'max-depth': 'error',
  'max-lines': ['error', { max: 500, skipBlankLines: true, skipComments: true }],
  'max-lines-per-function': ['error', { max: 50, skipBlankLines: true, skipComments: true }],
  'max-nested-callbacks': 'error',
  'max-params': ['error', { max: 5 }],
  'max-statements': ['error', { max: 20 }],

  /* ── Best practices & restrictions ──────────────────────────────────── */
  'accessor-pairs': 'error',
  'array-callback-return': 'error',
  'arrow-body-style': 'error',
  'block-scoped-var': 'error',
  camelcase: 'error',
  'capitalized-comments': 'error',
  'consistent-return': 'error',
  'consistent-this': 'error',
  curly: 'error',
  'default-case': 'error',
  'default-case-last': 'error',
  eqeqeq: 'error',
  'func-name-matching': 'error',
  'func-names': ['error', 'as-needed'],
  'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
  'grouped-accessor-pairs': 'error',
  'guard-for-in': 'error',
  'id-denylist': 'error',
  'id-length': 'error',
  'id-match': 'error',
  'logical-assignment-operators': 'error',
  'new-cap': 'error',
  'no-alert': 'error',
  'no-bitwise': 'error',
  'no-caller': 'error',
  'no-console': 'warn',
  'no-constructor-return': 'error',
  'no-continue': 'error',
  'no-div-regex': 'error',
  'no-else-return': 'error',
  'no-eq-null': 'error',
  'no-eval': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-label': 'error',
  'no-implicit-coercion': 'error',
  'no-implicit-globals': 'error',
  'no-inline-comments': 'error',
  'no-iterator': 'error',
  'no-label-var': 'error',
  'no-labels': 'error',
  'no-lone-blocks': 'error',
  'no-lonely-if': 'error',
  'no-multi-assign': 'error',
  'no-multi-str': 'error',
  'no-negated-condition': 'error',
  'no-nested-ternary': 'error',
  'no-new': 'error',
  'no-new-func': 'error',
  'no-new-wrappers': 'error',
  'no-object-constructor': 'error',
  'no-octal-escape': 'error',
  'no-param-reassign': 'error',
  'no-plusplus': 'error',
  'no-proto': 'error',
  'no-restricted-globals': ['error', { name: 'event', message: 'Use a local parameter instead.' }],
  'no-restricted-properties': [
    'error',
    { property: '__defineGetter__', message: 'Use Object.defineProperty instead.' },
  ],
  'no-restricted-syntax': [
    'error',
    { selector: 'ForInStatement', message: 'Use Object.keys/values/entries() instead of for…in.' },
  ],
  'no-return-assign': 'error',
  'no-script-url': 'error',
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-undef-init': 'error',
  'no-undefined': 'error',
  'no-underscore-dangle': 'error',
  'no-unneeded-ternary': 'error',
  'no-useless-call': 'error',
  'no-useless-computed-key': 'error',
  'no-useless-concat': 'error',
  'no-useless-rename': 'error',
  'no-useless-return': 'error',
  'no-var': 'error',
  'no-void': ['error', { allowAsStatement: true }],
  'no-warning-comments': 'error',
  'object-shorthand': 'error',
  'operator-assignment': 'error',
  'prefer-arrow-callback': 'error',
  'prefer-const': 'error',
  'prefer-exponentiation-operator': 'error',
  'prefer-named-capture-group': 'error',
  'prefer-numeric-literals': 'error',
  'prefer-object-has-own': 'error',
  'prefer-object-spread': 'error',
  'prefer-regex-literals': 'error',
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'error',
  radix: 'error',
  'require-unicode-regexp': 'error',
  strict: 'error',
  'symbol-description': 'error',
  'unicode-bom': 'error',
  'vars-on-top': 'error',
  yoda: 'error',
};
