import { defineConfig } from 'eslint/config';
import globals from 'globals';
import eslintPluginUnicorn from 'eslint-plugin-unicorn';
import eslintPluginImport from 'eslint-plugin-import';
import eslintPluginJsdoc from 'eslint-plugin-jsdoc';
import typescriptEslint from 'typescript-eslint';

export default defineConfig([
  {
    files: ['./packages/*/**/*.ts'],
    ignores: ['node_modules'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.node,
      },
    },
    plugins: {
      tsEslint: typescriptEslint,
      unicorn: eslintPluginUnicorn,
      import: eslintPluginImport,
      jsdoc: eslintPluginJsdoc,
    },
    extends: [typescriptEslint.configs.recommended],
    rules: {
      'constructor-super': ['error'],
      'for-direction': ['error'],
      'getter-return': ['error'],
      'no-async-promise-executor': ['error'],
      'no-case-declarations': ['error'],
      'no-class-assign': ['error'],
      'no-compare-neg-zero': ['error'],
      'no-cond-assign': ['error'],
      'no-const-assign': ['error'],
      'no-constant-binary-expression': ['error'],
      'no-constant-condition': ['error'],
      'no-control-regex': ['error'],
      'no-debugger': ['error'],
      'no-delete-var': ['error'],
      'no-dupe-args': ['error'],
      'no-dupe-class-members': ['error'],
      'no-dupe-else-if': ['error'],
      'no-dupe-keys': ['error'],
      'no-duplicate-case': ['error'],
      'no-empty': ['error'],
      'no-empty-character-class': ['error'],
      'no-empty-pattern': ['error'],
      'no-empty-static-block': ['error'],
      'no-ex-assign': ['error'],
      'no-extra-boolean-cast': ['error'],
      'no-fallthrough': ['error'],
      'no-func-assign': ['error'],
      'no-global-assign': ['error'],
      'no-import-assign': ['error'],
      'no-invalid-regexp': ['error'],
      'no-irregular-whitespace': ['error'],
      'no-loss-of-precision': ['error'],
      'no-misleading-character-class': ['error'],
      'no-new-native-nonconstructor': ['error'],
      'no-nonoctal-decimal-escape': ['error'],
      'no-obj-calls': ['error'],
      'no-octal': ['error'],
      'no-prototype-builtins': ['error'],
      'no-redeclare': ['error'],
      'no-regex-spaces': ['error'],
      'no-self-assign': ['error'],
      'no-setter-return': ['error'],
      'no-shadow-restricted-names': ['error'],
      'no-sparse-arrays': ['error'],
      'no-this-before-super': ['error'],
      'no-unassigned-vars': ['error'],
      'no-undef': ['error'],
      'no-unexpected-multiline': ['error'],
      'no-unreachable': ['error'],
      'no-unsafe-finally': ['error'],
      'no-unsafe-negation': ['error'],
      'no-unsafe-optional-chaining': ['error'],
      'no-unused-labels': ['error'],
      'no-unused-private-class-members': ['error'],
      'no-unused-vars': ['error'],
      'no-useless-assignment': ['error'],
      'no-useless-backreference': ['error'],
      'no-useless-catch': ['error'],
      'no-useless-escape': ['error'],
      'no-with': ['error'],
      'preserve-caught-error': ['error'],
      'require-yield': ['error'],
      'use-isnan': ['error'],
      'valid-typeof': ['error'],
      /* others */
      'accessor-pairs': ['error'],
      'array-callback-return': ['error'],
      'arrow-body-style': ['error'],
      'block-scoped-var': ['error'],
      camelcase: ['error'],
      'capitalized-comments': ['error'],
      'class-methods-use-this': ['error'],
      complexity: ['error'],
      'consistent-return': ['error'],
      'consistent-this': ['error'],
      curly: ['error'],
      'default-case': ['error'],
      'default-case-last': ['error'],
      'default-param-last': ['error'],
      'dot-notation': ['error'],
      eqeqeq: ['error'],
      'func-name-matching': ['error'],
      'func-names': ['error'],
      'func-style': ['error'],
      'grouped-accessor-pairs': ['error'],
      'guard-for-in': ['error'],
      'id-denylist': ['error'],
      'id-length': ['error'],
      'id-match': ['error'],
      'init-declarations': ['error'],
      'logical-assignment-operators': ['error'],
      'max-classes-per-file': ['error'],
      'max-depth': ['error'],
      'max-lines': ['error', { max: 500, skipBlankLines: true, skipComments: true }],
      'max-lines-per-function': ['error', { max: 50, skipBlankLines: true, skipComments: true }],
      'max-nested-callbacks': ['error'],
      'max-params': ['error', { max: 5 }],
      'max-statements': ['error', { max: 20 }],
      'new-cap': ['error'],
      'no-alert': ['error'],
      'no-array-constructor': ['error'],
      'no-await-in-loop': ['error'],
      'no-bitwise': ['error'],
      'no-caller': ['error'],
      'no-console': ['error'],
      'no-constructor-return': ['error'],
      'no-continue': ['error'],
      'no-div-regex': ['error'],
      'no-duplicate-imports': ['error'],
      'no-else-return': ['error'],
      'no-empty-function': ['error'],
      'no-eq-null': ['error'],
      'no-eval': ['error'],
      'no-extend-native': ['error'],
      'no-extra-bind': ['error'],
      'no-extra-label': ['error'],
      'no-implicit-coercion': ['error'],
      'no-implicit-globals': ['error'],
      'no-implied-eval': ['error'],
      'no-inline-comments': ['error'],
      'no-inner-declarations': ['error'],
      'no-invalid-this': ['error'],
      'no-iterator': ['error'],
      'no-label-var': ['error'],
      'no-labels': ['error'],
      'no-lone-blocks': ['error'],
      'no-lonely-if': ['error'],
      'no-loop-func': ['error'],
      'no-magic-numbers': ['error'],
      'no-multi-assign': ['error'],
      'no-multi-str': ['error'],
      'no-negated-condition': ['error'],
      'no-nested-ternary': ['error'],
      'no-new': ['error'],
      'no-new-func': ['error'],
      'no-new-wrappers': ['error'],
      'no-object-constructor': ['error'],
      'no-octal-escape': ['error'],
      'no-param-reassign': ['error'],
      'no-plusplus': ['error'],
      'no-promise-executor-return': ['error'],
      'no-proto': ['error'],
      'no-restricted-exports': ['off'],
      'no-restricted-globals': ['error', { name: 'event', message: 'Please use another name instead.' }],
      'no-restricted-imports': ['off'],
      'no-restricted-properties': [
        'error',
        {
          property: '__defineGetter__',
          message: 'Please use Object.defineProperty instead.',
        },
        {
          property: 'data',
          message: 'Please use another property name instead.',
        },
        {
          property: 'result',
          message: 'Please use another property name instead.',
        },
      ],
      'no-restricted-syntax': ['error'],
      'no-return-assign': ['error'],
      'no-script-url': ['error'],
      'no-self-compare': ['error'],
      'no-sequences': ['error'],
      'no-shadow': ['error'],
      'no-template-curly-in-string': ['error'],
      'no-ternary': ['off'],
      'no-throw-literal': ['error'],
      'no-undef-init': ['error'],
      'no-undefined': ['error'],
      'no-underscore-dangle': ['error'],
      'no-unmodified-loop-condition': ['error'],
      'no-unneeded-ternary': ['error'],
      'no-unreachable-loop': ['error'],
      'no-unused-expressions': ['error'],
      'no-use-before-define': ['error'],
      'no-useless-call': ['error'],
      'no-useless-computed-key': ['error'],
      'no-useless-concat': ['error'],
      'no-useless-constructor': ['error'],
      'no-useless-rename': ['error'],
      'no-useless-return': ['error'],
      'no-var': ['error'],
      'no-void': ['error'],
      'no-warning-comments': ['error'],
      'object-shorthand': ['error'],
      'one-var': ['off'],
      'operator-assignment': ['error'],
      'prefer-arrow-callback': ['error'],
      'prefer-const': ['error'],
      'prefer-destructuring': ['error'],
      'prefer-exponentiation-operator': ['error'],
      'prefer-named-capture-group': ['error'],
      'prefer-numeric-literals': ['error'],
      'prefer-object-has-own': ['error'],
      'prefer-object-spread': ['error'],
      'prefer-promise-reject-errors': ['error'],
      'prefer-regex-literals': ['error'],
      'prefer-rest-params': ['error'],
      'prefer-spread': ['error'],
      'prefer-template': ['error'],
      radix: ['error'],
      'require-atomic-updates': ['error'],
      'require-await': ['error'],
      'require-unicode-regexp': ['error'],
      'sort-imports': ['off'],
      'sort-keys': ['off'],
      'sort-vars': ['error'],
      strict: ['error'],
      'symbol-description': ['error'],
      'unicode-bom': ['error'],
      'vars-on-top': ['error'],
      yoda: ['error'],
      /* unicorn */
      'unicorn/filename-case': ['error', { case: 'camelCase' }],
      'unicorn/no-empty-file': ['error'],
      'unicorn/prefer-at': ['error'],
      'unicorn/prefer-includes': ['error'],
      'unicorn/prefer-node-protocol': ['error'],
      'unicorn/no-abusive-eslint-disable': ['error'],
      /* import */
      'import/order': [
        'error',
        {
          groups: ['builtin', 'internal', 'external', 'index', 'parent', 'sibling', 'object', 'type'],
          alphabetize: {
            order: 'asc',
          },
        },
      ],
      'import/no-dynamic-require': ['error'],
      /* jsdoc */
      'jsdoc/check-access': ['warn'],
      'jsdoc/check-alignment': ['warn'],
      'jsdoc/check-param-names': ['warn'],
      'jsdoc/check-property-names': ['warn'],
      'jsdoc/check-tag-names': ['warn'],
      'jsdoc/check-types': ['warn'],
      'jsdoc/check-values': ['warn'],
      'jsdoc/empty-tags': ['warn'],
      'jsdoc/implements-on-classes': ['warn'],
      'jsdoc/multiline-blocks': ['warn'],
      'jsdoc/no-multi-asterisks': ['warn'],
      'jsdoc/require-jsdoc': ['warn'],
      'jsdoc/require-param': ['warn'],
      'jsdoc/require-param-description': ['warn'],
      'jsdoc/require-param-name': ['warn'],
      'jsdoc/require-param-type': ['warn'],
      'jsdoc/require-property': ['warn'],
      'jsdoc/require-property-description': ['warn'],
      'jsdoc/require-property-name': ['warn'],
      'jsdoc/require-property-type': ['warn'],
      'jsdoc/require-returns': ['warn'],
      'jsdoc/require-returns-check': ['warn'],
      'jsdoc/require-returns-type': ['warn'],
      'jsdoc/require-yields': ['warn'],
      'jsdoc/require-yields-check': ['warn'],
      'jsdoc/tag-lines': ['warn'],
      'jsdoc/valid-types': ['warn'],
    },
  },
]);
