/* eslint-disable prefer-const, no-bitwise  */

import { describe, expect, it } from 'vitest';

import { Cyberflake } from '../src/cyberflake.js';

/**
 * Cyberflake Test Suite
 *
 * This test suite validates Cyberflake as a low-level, infrastructure-grade
 * identifier generator intended for use in distributed systems.
 *
 * The tests collectively define and enforce Cyberflake's public contract,
 * operational guarantees, and failure-mode behavior.
 *
 * Covered guarantees:
 *
 * - Uniqueness:
 *   Ensures that no two IDs generated by the same instance collide.
 *
 * - Monotonic ordering:
 *   Verifies that IDs are strictly increasing over time, within the same
 *   millisecond, and across logical time adjustments.
 *
 * - Deterministic time injection:
 *   Confirms that a custom time source can be injected for reproducible
 *   testing and controlled environments.
 *
 * - Sequence handling:
 *   Validates correct sequencing within the same millisecond and proper
 *   logical time advancement when the sequence space is exhausted.
 *
 * - Clock regression tolerance:
 *   Ensures that physical clock regressions do not break monotonic ordering
 *   through the use of a logical clock offset.
 *
 * - Bit layout and deconstruction correctness:
 *   Confirms that generated IDs can be losslessly decomposed into their
 *   constituent parts according to the defined bit layout.
 *
 * - Semantic validation (`isValid`):
 *   Verifies that structurally valid IDs are accepted and malformed,
 *   nonsensical, or out-of-contract values are defensively rejected.
 *
 * - Configuration guardrails:
 *   Ensures invalid `workerId` and `processId` configurations fail fast
 *   at construction time.
 *
 * - Long-running stability:
 *   Acts as a regression guard to ensure internal state consistency
 *   under prolonged ID generation.
 *
 * This suite is not intended to benchmark performance.
 * Performance characteristics are validated separately via dedicated
 * benchmark tests.
 */

describe('CyberFlake', () => {
  /**
   * Ensures that all IDs generated by a single Cyberflake instance
   * are globally unique within that instance.
   *
   * This test validates the most fundamental property of an ID generator:
   * no two calls to `generate()` may ever return the same identifier.
   *
   * The test generates a large number of IDs in rapid succession
   * using a single `(workerId, processId)` configuration and asserts that:
   *
   * - Each generated ID is distinct
   * - No collisions occur within the instance
   *
   * This guarantee is foundational for:
   * - Database primary keys
   * - Event identifiers
   * - Request / session correlation
   *
   * If this test fails, the generator is fundamentally broken and
   * must not be used in any production system.
   */
  it('generates unique IDs', () => {
    const cf = new Cyberflake({ workerId: 1, processId: 1 });
    const ids = new Set<string>();

    for (let i = 0; i < 10_000; i += 1) {
      ids.add(cf.generate());
    }

    expect(ids.size).toBe(10_000);
  });

  /**
   * Ensures that IDs are monotonically increasing as physical time advances.
   *
   * Cyberflake encodes the current timestamp as the most significant
   * portion of the identifier. As a result, IDs generated at later
   * points in time must always compare greater than those generated earlier.
   *
   * This test uses a deterministic, manually controlled time source
   * to simulate the passage of time and to verify that:
   * - Each increment in time results in a strictly greater ID
   * - No stale or out-of-order values are emitted
   * - Time-based ordering guarantees hold independently of sequence logic
   *
   * This behavior is foundational for:
   * - Chronological ordering of events
   * - Time-series data storage
   * - Distributed logging and tracing systems
   */
  it('generates monotonically increasing IDs over time', () => {
    let now = 1_700_000_000_000;

    const cf = new Cyberflake({
      workerId: 1,
      now: () => now,
    });

    const id1 = BigInt(cf.generate());
    now += 1;
    const id2 = BigInt(cf.generate());
    now += 1;
    const id3 = BigInt(cf.generate());

    expect(id2).toBeGreaterThan(id1);
    expect(id3).toBeGreaterThan(id2);
  });

  /**
   * Ensures correct sequencing when multiple IDs are generated
   * within the same millisecond.
   *
   * Cyberflake encodes a sequence counter to disambiguate IDs
   * generated at the same physical timestamp.
   *
   * When multiple IDs are produced within a single millisecond:
   * - The timestamp portion remains constant
   * - The sequence field increments monotonically
   * - Each resulting ID must be strictly greater than the previous one
   *
   * This test fixes the time source to a single millisecond and
   * generates multiple IDs in rapid succession, verifying that
   * the sequence mechanism alone is sufficient to preserve ordering
   * and uniqueness.
   *
   * This scenario represents the most common real-world usage pattern
   * for Cyberflake in high-throughput services.
   */
  it('handles multiple IDs within the same millisecond via sequence', () => {
    const fixedNow = 1_700_000_000_000;

    const cf = new Cyberflake({
      workerId: 1,
      now: () => fixedNow,
    });

    const ids = Array.from({ length: 100 }, () => BigInt(cf.generate()));

    for (let i = 1; i < ids.length; i += 1) {
      expect(ids[i]).toBeGreaterThan(ids[i - 1]);
    }
  });

  /**
   * Ensures that logical time advances correctly when the sequence space
   * is exhausted within a single millisecond.
   *
   * Cyberflake allows a fixed number of IDs to be generated per millisecond,
   * bounded by the size of the sequence field. When this limit is reached,
   * the generator must:
   *
   * - Advance the logical timestamp
   * - Reset the sequence counter
   * - Continue emitting strictly increasing IDs
   *
   * This test simulates a high-throughput burst by fixing the physical time
   * source and generating more IDs than the available sequence capacity.
   *
   * The test verifies that:
   * - No duplicate IDs are produced
   * - Monotonic ordering is preserved across the overflow boundary
   * - Logical time progression correctly compensates for sequence exhaustion
   *
   * This behavior is critical for systems that experience sudden bursts
   * of ID generation within the same millisecond.
   */
  it('advances logical time when sequence overflows', () => {
    const fixedNow = 1_700_000_000_000;

    const cf = new Cyberflake({
      workerId: 1,
      now: () => fixedNow,
    });

    const ids = Array.from({ length: 5_000 }, () => BigInt(cf.generate()));

    for (let i = 1; i < ids.length; i += 1) {
      expect(ids[i]).toBeGreaterThan(ids[i - 1]);
    }
  });

  /**
   * Ensures that monotonic ordering is preserved when the system clock
   * moves backwards.
   *
   * Distributed systems cannot assume a perfectly monotonic physical clock.
   * Time regressions may occur due to:
   * - NTP corrections
   * - VM snapshot restores
   * - Clock drift adjustments
   *
   * Cyberflake addresses this by maintaining a logical clock offset.
   * When the physical time regresses, the generator:
   * - Detects the regression
   * - Applies a logical offset to compensate
   * - Continues emitting monotonically increasing IDs
   *
   * This test simulates a backwards jump in the system clock and verifies
   * that the second generated ID is still strictly greater than the first,
   * preserving global ordering guarantees.
   */
  it('handles clock regression using logical offset', () => {
    let now = 1_700_000_000_010;

    const cf = new Cyberflake({
      workerId: 1,
      now: () => now,
    });

    const id1 = BigInt(cf.generate());

    // Simulate the system clock moving backwards
    now -= 10;

    const id2 = BigInt(cf.generate());

    // Monotonic ordering must be preserved despite clock regression
    expect(id2).toBeGreaterThan(id1);
  });

  /**
   * Ensures that a combination of clock regression and sequence overflow
   * does not break monotonic ordering or internal state consistency.
   *
   * This test targets one of the most pathological timing scenarios
   * a distributed ID generator can encounter:
   *
   * 1. A large number of IDs are generated within the same millisecond,
   *    fully exhausting the available sequence space.
   * 2. Immediately afterwards, the system clock moves backwards.
   *
   * In such a scenario, Cyberflake must:
   * - Preserve monotonic ordering guarantees
   * - Avoid emitting duplicate or decreasing IDs
   * - Correctly apply and maintain a logical clock offset
   * - Remain operational without throwing or stalling
   *
   * The test intentionally does not assert an exact numeric value.
   * Instead, it verifies that the generator continues to produce
   * a valid, non-negative, monotonically increasing identifier.
   *
   * This scenario is critical for real-world deployments where:
   * - Clock synchronization is imperfect
   * - High-throughput bursts occur
   * - Time regressions happen due to NTP corrections or VM restores
   */
  it('handles clock regression combined with sequence overflow', () => {
    let now = 1_700_000_000_000;

    const cf = new Cyberflake({
      workerId: 1,
      now: () => now,
    });

    // Exhaust the sequence space within a single millisecond
    for (let i = 0; i < 5_000; i += 1) {
      cf.generate();
    }

    // Simulate a backwards jump in the system clock
    now -= 100;

    const id = BigInt(cf.generate());

    // The generator must continue producing valid, ordered IDs
    expect(id).toBeGreaterThan(0n);
  });

  /**
   * Ensures that ID generation fails fast when the system clock
   * reports a time before the configured Cyberflake epoch.
   *
   * Cyberflake relies on a custom epoch as the reference point
   * for timestamp encoding. Any physical time earlier than this
   * epoch cannot be represented meaningfully within the bit layout.
   *
   * Rather than attempting to clamp or correct such values,
   * Cyberflake explicitly fails fast by throwing a `RangeError`.
   *
   * This behavior is intentional and enforces the following guarantees:
   * - Prevents generation of semantically invalid IDs
   * - Avoids silent corruption of the timestamp field
   * - Surfaces clock misconfiguration immediately and loudly
   *
   * This test simulates an invalid system clock by injecting
   * a time source that returns a value earlier than the epoch.
   */
  it('throws if system time is before epoch', () => {
    const cf = new Cyberflake({
      workerId: 1,
      now: () => 1,
    });

    expect(() => cf.generate()).toThrow(RangeError);
  });

  /**
   * Ensures that `deconstruct` correctly extracts all components
   * from a generated Cyberflake ID.
   *
   * This test verifies the structural correctness of the decoding process:
   *
   * - `workerId` is recovered exactly from the encoded bit field
   * - `processId` is recovered exactly from the encoded bit field
   * - `timestamp` reflects the original time source used during generation
   * - `sequence` starts from zero for the first ID in a given millisecond
   * - `binary` representation respects the configured bit layout
   *
   * Correct deconstruction is essential for:
   * - Observability and tracing systems
   * - Debugging and forensic analysis
   * - Validating bit layout changes or optimizations
   *
   * A deterministic time source is used to ensure reproducibility
   * and to isolate decoding logic from time-related variability.
   */
  it('deconstructs ID into correct components', () => {
    let now = 1_700_000_000_000;

    const cf = new Cyberflake({
      workerId: 7,
      processId: 3,
      now: () => now,
    });

    const id = cf.generate();
    const data = cf.deconstruct(id);

    expect(data.workerId).toBe(7);
    expect(data.processId).toBe(3);
    expect(data.timestamp).toBe(now);
    expect(data.sequence).toBe(0);
    expect(data.binary.length).toBeLessThanOrEqual(63);
  });

  /**
   * Ensures consistency between ID generation and deconstruction.
   *
   * This test validates the round-trip contract of Cyberflake identifiers:
   *
   *   generate() → deconstruct() → original components
   *
   * An ID produced by `generate()` must be fully and losslessly
   * decomposable back into its constituent parts.
   *
   * Specifically, this test guarantees that:
   * - `workerId` encoded into the ID is recovered exactly
   * - `processId` encoded into the ID is recovered exactly
   * - `timestamp` encoded into the ID matches the original time source
   *
   * This property is essential for:
   * - Debugging and observability
   * - Auditing and tracing workflows
   * - Downstream systems that rely on embedded metadata
   *
   * The use of a deterministic time source ensures that
   * time-related assertions remain stable and reproducible.
   */
  it('maintains consistency between generate and deconstruct', () => {
    let now = 1_700_000_000_000;

    const cf = new Cyberflake({
      workerId: 12,
      processId: 7,
      now: () => now,
    });

    const id = cf.generate();
    const data = cf.deconstruct(id);

    expect(data.workerId).toBe(12);
    expect(data.processId).toBe(7);
    expect(data.timestamp).toBe(now);
  });

  /**
   * Ensures that `isValid` accepts IDs generated by Cyberflake itself.
   *
   * This test defines the positive contract of `isValid`:
   *
   * - Any ID produced by `Cyberflake.generate()` must be considered valid
   * - No false negatives are allowed for internally generated identifiers
   *
   * This guarantee is critical because:
   * - `isValid` may be used as a guard before persistence or transmission
   * - False rejections would break otherwise correct application flows
   * - Internally generated IDs represent the canonical reference format
   *
   * The test intentionally uses the simplest valid configuration
   * to isolate the validation logic from configuration complexity.
   */
  it('validates correct IDs with isValid()', () => {
    const cf = new Cyberflake({ workerId: 1 });
    const id = cf.generate();

    expect(Cyberflake.isValid(id)).toBe(true);
  });

  /**
   * Ensures that negative numeric values are never considered valid IDs.
   *
   * Cyberflake identifiers are defined over a strictly non-negative
   * integer domain. All valid IDs are encoded as unsigned bit sequences
   * derived from time, worker/process identifiers, and sequence counters.
   *
   * Allowing negative values would:
   * - Violate the bit-level encoding model
   * - Break monotonic ordering guarantees
   * - Introduce undefined behavior during bit-shift and masking operations
   *
   * For these reasons, `isValid` rejects any negative numeric input
   * unconditionally and without attempting further validation.
   */
  it('rejects negative numeric IDs', () => {
    expect(Cyberflake.isValid('-5')).toBe(false);
  });

  /**
   * Ensures that empty or whitespace-only inputs are explicitly rejected.
   *
   * Although certain JavaScript runtimes or transpilation paths may
   * coerce such inputs during `BigInt` parsing, Cyberflake treats them
   * as invalid by design.
   *
   * Accepting empty or whitespace-only identifiers would:
   * - Introduce ambiguous behavior across runtimes
   * - Mask accidental bugs at call sites
   * - Violate the expectation that a cyberflake represents
   *   an explicit, intentional identifier
   *
   * This test enforces strict input hygiene and guarantees that
   * `isValid` behaves deterministically and defensively.
   */
  it('rejects empty or whitespace-only IDs', () => {
    expect(Cyberflake.isValid('')).toBe(false);
    expect(Cyberflake.isValid('   ')).toBe(false);
  });

  /**
   * Ensures that invalid `workerId` values are rejected at construction time.
   *
   * The `workerId` uniquely identifies a logical node or service instance
   * within a distributed Cyberflake deployment.
   *
   * Because `workerId` is encoded into a fixed-width bit field:
   * - Values outside the allowed range cannot be represented correctly
   * - Silent truncation via bit masking would corrupt namespace isolation
   * - ID collisions would become possible without any runtime signal
   *
   * To prevent these failure modes, Cyberflake enforces strict validation
   * and fails fast by throwing a `RangeError` when an invalid `workerId`
   * is provided during initialization.
   *
   * This test verifies that:
   * - Negative `workerId` values are rejected
   * - Excessively large `workerId` values are rejected
   * - Misconfiguration is detected immediately rather than at runtime
   */
  it('throws if workerId is out of range', () => {
    expect(() => new Cyberflake({ workerId: -1 })).toThrow(RangeError);
    expect(() => new Cyberflake({ workerId: 999 })).toThrow(RangeError);
  });

  /**
   * Ensures that invalid `processId` values are rejected at construction time.
   *
   * Cyberflake relies on `(workerId, processId)` pairs to provide
   * namespace isolation across distributed instances.
   *
   * Allowing an out-of-range `processId` would:
   * - Break the bit layout contract
   * - Cause silent truncation during bit masking
   * - Lead to unexpected ID collisions
   *
   * For this reason, Cyberflake applies strict validation and
   * fails fast by throwing a `RangeError` during initialization
   * rather than allowing an invalid configuration to proceed.
   *
   * This test verifies that defensive configuration validation
   * is enforced and that misconfigurations surface immediately.
   */
  it('throws if processId is out of range', () => {
    expect(() => new Cyberflake({ workerId: 1, processId: 999 })).toThrow(RangeError);
  });

  /**
   * Ensures that multiple Cyberflake instances with different
   * `(workerId, processId)` pairs do not produce colliding IDs.
   *
   * This test validates Cyberflake's core distributed-systems contract:
   *
   * - Each `(workerId, processId)` pair defines an isolated ID namespace
   * - IDs generated in parallel namespaces must never collide
   * - No shared state or coordination is required between instances
   *
   * The test uses a fixed timestamp to eliminate time as a variable,
   * ensuring that any difference in generated IDs is solely the result
   * of worker/process isolation encoded in the bit layout.
   *
   * This behavior is critical for:
   * - Multi-process deployments (PM2, Node.js cluster)
   * - Containerized environments (Kubernetes pods)
   * - Horizontally scaled services sharing a common ID format
   *
   * Note:
   * This test does not attempt to detect misconfiguration.
   * If two instances are configured with the same `(workerId, processId)`,
   * collisions are expected and considered a configuration error.
   */
  it('does not collide across instances with different worker/process pairs', () => {
    const now = 1_700_000_000_000;

    const cf1 = new Cyberflake({
      workerId: 1,
      processId: 1,
      now: () => now,
    });

    const cf2 = new Cyberflake({
      workerId: 2,
      processId: 1,
      now: () => now,
    });

    const id1 = cf1.generate();
    const id2 = cf2.generate();

    expect(id1).not.toBe(id2);
  });

  /**
   * Ensures long-term stability during continuous ID generation.
   *
   * This test validates that a Cyberflake instance remains internally
   * consistent over a prolonged generation cycle.
   *
   * The following guarantees are implicitly verified:
   * - Monotonic ordering is preserved across many consecutive generations
   * - Internal state (timestamp, sequence, offset) does not corrupt over time
   * - No integer overflow or wrap-around occurs in normal operation
   * - Logical clock handling remains stable under sustained load
   *
   * This test acts as a regression guard against subtle state-related bugs
   * that may only surface after many iterations rather than in short runs.
   *
   * Note:
   * This is not a performance benchmark. The iteration count is chosen
   * to be large enough to stress state transitions while remaining fast
   * enough for unit test execution.
   */
  it('remains stable under continuous generation', () => {
    const cf = new Cyberflake({ workerId: 1 });

    let last = BigInt(cf.generate());

    for (let i = 0; i < 50_000; i += 1) {
      const next = BigInt(cf.generate());

      // Each newly generated ID must be strictly greater than the previous one
      expect(next).toBeGreaterThan(last);

      last = next;
    }
  });

  /**
   * Validates that `isValid` defensively rejects inputs that are
   * not semantically meaningful cyberflake identifiers.
   *
   * This test group focuses on *input sanitization* and *structural validity*,
   * not on whether an ID was actually generated by Cyberflake.
   *
   * Covered cases:
   * - Non-numeric input
   * - Negative values
   * - Empty or whitespace-only strings
   *
   * These cases are rejected early to prevent undefined behavior
   * and to clearly define the public contract of `isValid`.
   */
  it('rejects malformed or nonsensical IDs with isValid()', () => {
    expect(Cyberflake.isValid('not-a-number')).toBe(false);
    expect(Cyberflake.isValid('-1')).toBe(false);
    expect(Cyberflake.isValid('')).toBe(false);
    expect(Cyberflake.isValid('   ')).toBe(false);
  });

  /**
   * Ensures that IDs exceeding the configured bit layout are rejected.
   *
   * Cyberflake IDs are constrained by a fixed bit layout.
   * Any value whose binary representation exceeds this layout
   * cannot be a valid cyberflake, regardless of its numeric value.
   *
   * This test explicitly constructs a value that overflows the
   * maximum allowed bit length to validate this constraint.
   */
  it('rejects IDs exceeding the configured bit layout length', () => {
    // Force a value larger than the maximum supported bit width
    const invalid = (1n << 70n).toString();
    expect(Cyberflake.isValid(invalid)).toBe(false);
  });

  /**
   * Ensures that enabling deterministic mode without an explicit time source
   * fails fast at construction time.
   *
   * Deterministic mode exists to guarantee fully reproducible output in tests,
   * benchmarks, and controlled environments. Allowing it to silently fall back
   * to `Date.now` would defeat that guarantee and mask configuration mistakes.
   *
   * Cyberflake therefore treats `deterministic: true` without a `now` function
   * as a configuration error and throws a `RangeError` immediately.
   */
  it('throws when deterministic mode is enabled without a time source', () => {
    expect(() => new Cyberflake({ workerId: 1, deterministic: true })).toThrow(RangeError);
  });

  /**
   * Ensures that deterministic mode operates normally when an explicit time
   * source is supplied.
   *
   * When both `deterministic: true` and a `now` function are provided, the
   * generator must construct successfully and produce valid identifiers driven
   * exclusively by the injected clock.
   */
  it('generates valid IDs in deterministic mode with an explicit time source', () => {
    const fixedNow = 1_700_000_000_000;

    const cf = new Cyberflake({
      workerId: 1,
      deterministic: true,
      now: () => fixedNow,
    });

    const id = cf.generate();

    expect(Cyberflake.isValid(id)).toBe(true);
    expect(cf.deconstruct(id).timestamp).toBe(fixedNow);
  });
});
